$(function(){
//ESTABELECEMOS UM EVENTO DE CLIQUE NO LINK DO MENU "a"
	$('a').click(function(){

//CRIAMOS UMA VARIAVEL QUE OBTEM O VALOR DO ATRIBUTO "href"	
		var href = $(this).attr('href');

//CRIAMOS OUTRA VARIAVEL PARA MEDIR A DISTÂNCIA ENTRE O TOPO DA PÁGINA E O ELEMENTO QUE SEJA CLICADO
		var offSetTop = $(href).offset().top;

/*APÓS CRIARMOS ESSA LÓGICA, ANIMAMOS O PROCESSO DE SCROLLAGEM ATRAVÉS DO "scrollTop" ATRELADA
A LÓGICA QUE CALCULAMOS ENTRE O TOPO DA PÁGINA E O TOPO DA SESSÃO DO LINK QUE FOR CLICADO*/	
		$('html,body').animate({'scrollTop':offSetTop});

//RETURN FALSE PARA NÃO ATUALIZAR A PÁGINA AO CLICAR NO LINK		
		return false;
	})
})